version: '3.7'

services:
  application: 
    container_name: captcha-app
    build: .
    hostname: captcha-app
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - database

  database: 
    image: mongo
    container_name: database
    hostname: databasehost
    ports:
        - '27017-27019:27017-27019'
    volumes: 
      - mongodbdata:/data/db
      
volumes:
  mongodbdata:
    driver: local