version: '3.7'

networks:
  captcha-network:

services:
  application: 
    container_name: captcha-app
    build: .
    hostname: captcha-app
    networks:
      - captcha-network
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - database

  database: 
    container_name: database
    image: mongo
    hostname: databasehost
    networks:
      - captcha-network
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_DATABASE: captchadatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  dbdata: